### PR TITLE
fix: add control panel State Off on keypad

### PR DESCRIPTION
**Pull request by kvanbiesen**
Needs Major revisioning as i did this on my phone and couldnt really test it???

### CODE REVIEW

**Comment by fuatakgun** [comment]
please test this as it would probably effect the front end component

**Comment by kvanbiesen** [comment]
There, tested and working,

alarm_off function gets added to the "eufy_security" domain. 
Now if you have a keypad, it sees 2 states. Off or Disarmed.

- Tested with changing tru the app.
- Tested changing with the control pannel. Off button changes state in the app to off and in HA.
- Tested changing in HA
- Tested with node-red 
- State get updated to off for the homebase, or disarmed, whatever you pick.
- Dunno what else to test

Doesnt change anything on the frontend. Only HA states are correctly updated plus you can set the alarm to off or disarmed/  **1 thing i cant test, if you dont have an keypad and you call the function....alarm_off** (maybe make a note that it only works on keypad)

Everything seems to be working, no errors or crashes. Doesnt change anything that i notice.

Running latest bropat, havent tested with older, should be a problem. The undefined status in the ws from bropat still shows up but doesnt affect anything. That's a bropat issue..

**Comment by kvanbiesen** [comment]
Ps Pushed it into master for easier merging :)

**Comment by fuatakgun** [comment]
Thanks for testing, so if it is actually off, do you still see unknown?

**Comment by kvanbiesen** [comment]
Nope. It says off in homeassistent if you set it by whatever device to off.
(Keypad, app, automation).


The only undefined it's throwing , is in bropats WS, but it doesn't affect
anything. It sends the right command, it just isn't defined but works.

On your end and ha everything works

**Comment by kvanbiesen** [comment]
Status home:

Schermafbeelding 2023-08-09 092845
Schermafbeelding 2023-08-09 092900

Switched to Off by keypad or app or HA or the eufy_security -> alam_off function.
Schermafbeelding 2023-08-09 092934
Schermafbeelding 2023-08-09 092920


As i said, it is working, but cant test it if you call this function and do not have a keypad. (As i have keypad)

**Comment by fuatakgun** [comment]
Thank you very much, merged

**Pull request merged**
