### PR TITLE
feat: Added new Homebase 3 and Cam3 pro to device list

### PR DESCRIPTION
**Pull request by trushank**
The new devices cause the integration to crash with this message:  "Exception - process_messages: 18 is not a valid DEVICE_TYPE" This will add support for those devices.

### CODE REVIEW

**Review by KyleDoherty1 — APPROVED** [review]

**Comment by cdnninja** [comment]
@trushank i see you cancelled this.  Is it no longer required?

**Comment by Hyabusa64** [comment]
has the issue been fixed?

**Comment by trushank** [comment]
How do I merge this PR?
I assumed close PR would merge it

**Comment by cdnninja** [comment]
I have merged this. Thank you for this!

**Comment by KyleDoherty1** [comment]
@cdnninja @trushank still getting the following error:

> 2022-10-12 08:24:24.236  ERROR P2PClientProtocol.lookup(): station: T8030P2322290D06 - All address lookup tentatives failed. 
> 2022-10-12 08:24:24.238  INFO  Timeout connecting to station T8030P2322290D06 

Does the version have to be incremented? @trushank did this work for you?

**Comment by cdnninja** [comment]
Yeah I need to get GitHub to increment.  For some reason the action didn't work for that.  Didn't get time to troubleshoot that.  You can pull the latest branch in HACS though.

**Comment by ajma** [comment]
not trying to be nitpicky here but it seems like Eufy is switching up the model naming structure and we should call it CAMERA_S330 instead of CAMERA3_PRO (also I don't think they're calling this pro). wdyt?

**Pull request merged**
