### PR TITLE
feat: new major version - breaking changes

### PR DESCRIPTION
**Pull request by fuatakgun**
BREAKING CHANGE: Read below
BREAKING CHANGES: Read below

This is a breaking change and will probably require you to rework your existing automations and dashboards.
If you are happy with your current setup, there is no urgency to migrate but your integration might become inoperational in the future.

### CODE REVIEW

**Comment by thomasgeens** [comment]
Hi @fuatakgun , is it also a breaking change from 5.3.3 to 6.x?
And will you still be releasing new previews on 5.x?

**Comment by fuatakgun** [comment]
Nope, v5.x was manual release number v6.x is automatically released but they are compatible

**Comment by thomasgeens** [comment]
Thanks, good news! And where will you be releasing the previews, as with 5 alpha previously?

**Comment by fuatakgun** [comment]
Alpha or v5 was intended to release by hand until it reaches into maturity. When it was at good level, i merged alpha into master and it became v6. From now on, every change will be on master and v6. I don't think we need a preview release as of now.

**Pull request merged**
